### PR TITLE
add-rpc-provider-zeus

### PR DESCRIPTION
**Pull request by ctrl-alt-lulz**

### CODE REVIEW

**Comment by taxmeifyoucan** [comment]
Is the endpoint working correctly? I am getting incorrect responses 
```
curl -s -X POST  https://eth.ephemeral.zeus.fyi  -H "Content-Type: application/json" --data '{"jsonrpc":"2.0", "method":"eth_blockNumber", "params":[''], "id":1}'
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x0"
}
```

**Comment by ctrl-alt-lulz** [comment]
> Is the endpoint working correctly? I am getting incorrect responses
> 
> ```
> curl -s -X POST  https://eth.ephemeral.zeus.fyi  -H "Content-Type: application/json" --data '{"jsonrpc":"2.0", "method":"eth_blockNumber", "params":[''], "id":1}'
> {
>   "jsonrpc": "2.0",
>   "id": 1,
>   "result": "0x0"
> }
> ```

Thanks for checking! Hmm it appears something odd is going on. I did update it to use choreography to reset the chain before the latest reset, and thought maybe that could have had an issue, but it wasn't that. I recreated a new beacon and had the same issue and also shelled into geth's container and attached to the ipc and it's at 0 blocks as well there. Hmm maybe it could be a peer count thing. Gonna figure it out + add some observability & automated checking over next week before merging in.

the beacon does connect to the engine api fine it appears

i think maybe it's downloading an out of date or wrong genesis? I have it always pulling the latest release by default

Downloading https://github.com/pk910/test-testnet-repo/releases/download/ephemery-39/testnet-all.tar.gz...

manually checked and it has this:
export ITERATION_NUMBER="39"
export ITERATION_RELEASE="ephemery-39"
export GENESIS_TIMESTAMP="1671994800"
export GENESIS_RESET_INTERVAL="172800"

is the genesis time for eth/v1/beacon/genesis supposed to equal the genesis time in retention.vars?
```
{
    "data": {
        "genesis_time": "1671995100",
        "genesis_validators_root": "0xf3e30c881fcbd073f84a63b2275ae504255ed90e61d405eebaaa42af59da61bd",
        "genesis_fork_version": "0x1000101b"
    }
}
```

{"msg":"Execution engine online","level":"INFO","ts":"2022-12-26T02:16:41.888118315Z","service":"exec"}

In geth logs

Left PoW stage
Looking for peers                        peercount=1 tried=106 static=0
Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!
 
instance: Geth/v1.10.26-stable-e5eb32ac/linux-amd64/go1.18.8
at block: 0 (Sun Dec 25 2022 19:00:00 GMT+0000 (UTC))
 datadir: /data
 modules: admin:1.0 debug:1.0 engine:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

To exit, press ctrl-d or type exit
> eth.blockNumber
0

--- ah
i think i know what the issue is, i was redownloading the configs, but using the same startup cli, I think I need to also update this on reset

--networkid=1337531 \

should be 1337537 now, once I get that updated into the choreography it should be all good on resets from now on I think

**Comment by ctrl-alt-lulz** [comment]
should all be working now and has choreography confirmed to work on reset. it's also set up so I'll know if there's an issue to repair. ready 4 merge :)

**Comment by taxmeifyoucan** [comment]
Awesome, works well now!  Thanks

**Pull request merged**
